### ISSUE TITLE
Memory Leak: Watchers are not torn down properly on route change

### ISSUE THREAD

**Issue by jgrund** [artch/angular-route-segment#106]
When a route changes, any watcher properties do not seem to be destroyed. Instead they live on in `$rootScope` leaking memory and making more calls. 

Because the reference is lost once we change routes, we can no longer GC and destroy the watcher. 
This ends up compounding the issue and can be quite bad.

**Comment by wayneseymour** [comment]
:+1:

**Comment by johnsonw** [comment]
:+1:

**Comment by johnsonw** [comment]
Please expedite this if possible.

**Comment by jgrund** [comment]
@artch Any idea on this test run? doesn't seem relative to my changes:

https://travis-ci.org/artch/angular-route-segment/builds/83714232
