### ISSUE TITLE
<div app-view-segment="1"></div> does not work inside ng-if

### ISSUE THREAD

**Issue by IKoshelev** [artch/angular-route-segment#56]
Good day again, Artem.

We have a nested route where we only want to load segments after the first if the first one  successfully loaded data. We are using ```resolve:{...}``` in the route and in the template of first segment:
```
<div ng-if="group"> 
     <div app-view-segment="1"></div>
</div>
```
It doesn't work - the element gets added to the DOM, but the segment doesn't show up inside it.

We found a workaround like this
```
    <script type="text/ng-template" id="app-view-segment1.html">
         <div app-view-segment="1"></div>
    </script>

   <div ng-if="group"> 
        <div class="span10 early-full-width">
              <div ng-include=" 'app-view-segment1.html' "></div>
       </div>
    </div>
```
but since this looks like a bug - maybe a permanent fix is in order.

**Comment by vdsabev** [comment]
We have the same issue, and since we can't have the `ng-if` in each segment template due to css specifics, we're using the workaround that @IKoshelev mentioned:
```html
<div ng-if="ready" ng-include="::'segment.html'"></div>
```
And in the included template `segment.html`:
```html
<div app-view-segment="1"></div>
```

**Comment by jeserkin** [comment]
Why doesn't it work around `="0"`? Is there any fundamental reason, why shouldn't work?
