### ISSUE TITLE
Provide npm module for those of us

### ISSUE THREAD

**Issue by fineswap** [artch/angular-route-segment#69]
Hi there, thanks for the module!

This will be quick: Is it possible to publish it as an independent npm module for those of us who don't use Bower?

**Comment by robhicks** [comment]
+1 for this. Using npm also works with [webpack](http://webpack.github.io/)

**Comment by martinssipenko** [comment]
:+1:

**Comment by artch** [comment]
Done: https://www.npmjs.com/package/angular-route-segment
